apiVersion: v1
kind: Namespace
metadata:
  name: mezan-ORCHEX-dev
  labels:
    name: mezan-ORCHEX-dev
    environment: development
    app.kubernetes.io/name: mezan-ORCHEX
    app.kubernetes.io/instance: dev