version: "1.0"
quality:
  gates:
    pre_commit:
      - lint_check
      - type_check
      - format_check
      - secret_scan

    pre_merge:
      - unit_tests
      - integration_tests
      - security_scan
      - coverage_threshold

    pre_release:
      - e2e_tests
      - performance_tests
      - accessibility_audit
      - manual_qa_signoff

  thresholds:
    coverage:
      minimum: 80
      target: 90

    performance:
      lighthouse_score: 90
      lcp_ms: 2500
      fid_ms: 100
      cls: 0.1

    accessibility:
      wcag_level: "AA"
      lighthouse_a11y: 90

    security:
      critical_vulnerabilities: 0
      high_vulnerabilities: 0

  release_criteria:
    production:
      - all_gates_passed
      - no_critical_bugs
      - documentation_updated
      - changelog_updated
      - stakeholder_approval

    staging:
      - pre_merge_gates_passed
      - smoke_tests_passed

  metrics:
    tracked:
      - test_coverage
      - bug_escape_rate
      - mean_time_to_fix
      - deployment_frequency
      - change_failure_rate

    reporting:
      frequency: weekly
      destination: "docs/quality/"
